### ISSUE TITLE
Setup instructions: SQLite Manager not compatible with current version of Firefox

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/sql-ecology-lesson#213] opened 2018-03-19 11:32 UTC
From Fergus Keatinge:

Just an FYI for the Data Carpentry Workshop Setup Instructions - SQLite Manager is no longer compatible with the current version of Firefox (which is linked on the instructions page) - as per SQLite Manager addon page:

"This extension depended upon the interface to sqlite engine embedded in Firefox. As the interface has been removed in Firefox 57, this extension no longer functions. However, the extension can be used on ESR release of Firefox, which can be downloaded at https://www.mozilla.org/en-US/firefox/organizations/all/."

Therefore requiring the user to download the ESR version of Firefox (Firefox Setup 52.7.2esr.exe) , this may want to be included in the set up instructions, as it may not be clear to non-technical participants.

**Comment by remram44** [comment] 2018-03-19 15:04
Duplicate of #199

**Closed** 2018-03-19 15:05 UTC
Labels: bug
