### ISSUE TITLE
Define "manager"

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/sql-ecology-lesson#373] opened 2024-03-02 01:01 UTC
### How could the content be improved?

In the `JOIN` section, we refer to the "manager" but we never define what the manager is.  

### Which part of the content does your suggestion apply to?

https://datacarpentry.org/sql-ecology-lesson/aio.html#joins

**Comment by adamancer** [comment] 2024-03-09 00:00
Thanks for the suggestion! A previous issue identified the same problem with how "manager" is used in the lesson, so I'm going to close this one but you can refer to #345 for updates.

**Comment by adamancer** [comment] 2024-03-09 00:01
Duplicate of #345

**Closed by adamancer** 2024-03-09 00:01 UTC
