### ISSUE TITLE
Database types issues witDB Browser  

### ISSUE THREAD

**Issue by orchid00** [datacarpentry/sql-ecology-lesson#223] opened 2018-06-12 18:50 UTC
Hello Maintainers!

I hope you are doing well!
Today June 12th, 2018, during a data carpentry workshop SQL lesson. We discovered some little nuances about types.

I'm new to DB Browser although I have experienced with databases.
DB Browser might have some issues

For example, 

```
SELECT MAX(weight), MIN(weight), AVG(weight), COUNT(weight)
FROM surveys;
```
for some reason shows this

MAX(weight)|MIN(weight)|AVG(weight)|COUNT(weight)
---|---|---|---
0  |4.0   |38.7519761456018|35549

So we had to exclude the empty weights

this new query, **however**, returned the same table as above
```
SELECT MAX(weight), MIN(weight), AVG(weight), COUNT(weight)
FROM surveys
WHERE weight IS NOT NULL;
```

So new query

```
SELECT MAX(weight), MIN(weight), AVG(weight), COUNT(weight)
FROM surveys
WHERE weight != '';
```
worked

MAX(weight)|MIN(weight)|AVG(weight)|COUNT(weight)
---|---|---|---
280.0  |4.0   |38.7519761456018|35549

In case you are wondering if it is a problem with the data structure of Table surveys
Please see:

```
CREATE TABLE "surveys" (
	`record_id`	INTEGER,
	`month`	INTEGER,
	`day`	INTEGER,
	`year`	INTEGER,
	`plot_id`	INTEGER,
	`species_id`	TEXT,
	`sex`	TEXT,
	`hindfoot_length`	REAL,
	`weight`	REAL
)
```
This is an import from the csv surveys and then changed the data type following the intro data types
http://www.datacarpentry.org/sql-ecology-lesson/00-sql-introduction (at the bottom)

Any ideas, suggestions, what this issue might be or how should we proceed?
Thanks for your time

**Comment by remram44** [comment] 2018-06-12 18:59
Hi @orchid00! Thanks for reporting this, it is actually a duplicate of #211. I have patched DB Browser already (https://github.com/sqlitebrowser/sqlitebrowser/pull/1349), so the next version shouldn't be affected -- but perhaps we should update the instructor guide to make everyone aware of this issue, the fact that it might only affect some versions of the software, and the fix (which you mentioned, checking for empty strings).

**Comment by ChristinaLK** [comment] 2020-08-12 02:54
Sounds like the software was patched to solve this problem, so I will close this issue.

**Closed by ChristinaLK** 2020-08-12 02:54 UTC
Labels: type:bug, type:instructor guide
